### DISCUSSION TITLE
Feature: grouped collections

### DISCUSSION THREAD

**Discussion by Skrubbadubba** [StaticJsCMS/static-cms#316] [Ideas]
The idea is that you could group multiple different collections inside collections. This would replace, or maybe you could say be another iteration of, nested collections. Obviously, you would only be able to create entries at the deepest level of the collections tree, i.e you shoudn't be able to create collections as entries, im just suggesting to be able to group them.

I made another suggestion here https://github.com/StaticJsCMS/static-cms/discussions/315, about headers. Having headers would help with visual grouping, and is (I'm guessing) way more efficient in terms of cost of development/UX improvement, but being able to hide collections within dropdowns is certainly an improvement over that.

What this would add over current nested collections:
Currently nested collections expects a certain folder structure:
```
content
└── pages
    ├── authors
    │   ├── author-1
    │   │   └── index.md
    │   └── index.md
    ├── index.md
    └── posts
        ├── hello-world
        │   └── index.md
        └── index.md
```
Grouped collections would allow any folder structure,  for example:
```
content
└── pages
    ├── authors
    │   ├── author-1.md
    │   └── author-2.md
    ├── index.md
    └── posts
        ├── hello-world.md
        ├── goodbye-world.md
        └── index.md
```
which obviously improves flexibility but also makes adding staticCMS to an already existing project much easier. A project with a lot of content already added might require a lot of monotonous work just renaming files and creating folders to get working with nested collections

Grouped collections would also allow differently configured collections to be grouped. This would be very useful, say if you wanted a collection for your site's pages, but some pages need another set of fields because they have a special layout or componentry (like a landing page for example). It would also allow having, say, a file collection with settings over a group of similar pages be close both visually and in terms of "clicks away" to the folder collection with those pages.

This would be a new collection type, besides file and folder collections, and be defined with a special `collections` option.

Speaking from inexperience, it sounds to me like it wouldn't be the hardest thing to implement - not a lot of backend stuff. Since regular, already functional collections - the ones at the deepest level of the collection group - would handle actually creating and editing entries, the only thing that needs adding development-wise is being able to read a config.yaml with grouped collections, and using the dropdown UI feature already used by nested collections to group them. 

Additional suggestions:
The ability to create collection "templates". That way you wouldn't need to copy paste a bunch of similar collections with different names inside a collection group, You could just configure different `name`, `label`, and `folder/file` and apply a predefined set of fields. 

Also, with this in place, it would actually be possible to create collections as entries inside a collection group. The most obvisouly use case being creating a new page route with it's own sub pages, insides a "pages" collection. Otherwise functionality would be limited to only creating new pages at the deepest level of the already existing sitemap.

With all of this in mind, this is how a config.yaml could look:
``` yaml
backend blablabla
<truncated>

collections:

  - template: basic-page
    fields:
      - label: Title
        name: title
        widget: string
        pattern: ['.{20,}', Must have at least 20 characters]
      - {label: Layout, name: layout, widget: select, options: [news, guides]}
      - {label: Featured Image, name: thumbnail, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: pages
    label_singular: page
    create: 
       true   
    collections:
      - name: news
        label: news
        folder: src/pages/news
        fields:
          - {{basic-page}} //Not sure what the "yaml-onic" way of using a variable like this is
      - name: guides
        label: Guides
        folder: src/pages/guides
        fields:
           - {{basic-page}}
      - name: about
        label: About us
        folder: src/pages/about
        fields:
          - {{basicpage}}
          - label: Editors
            name: editors
            widget: list
            fields:
            - {label: Socials, name: socials, widget: list}
            - {label: About me, name: body, widget, markdown}
      - name: start
        label: Start page
        collections: 
          - name: page
            label: The page
            file: src/pages/index.md
            fields:
              - {{basic-page}}
              //Too tired now, but imagine there would be fields specific to the start page here
          - name: settings
            label: Settings
            file: src/settings/start-page.json
            fields:
              //Same thing here I don't know what to write anymore, but you get the idea

```

IMO this is the way netlify-CMS should have implemented nested collections to begin with.
