### ISSUE TITLE
date fields won't display in summaries (or as sortable fields)

### ISSUE THREAD

**Issue by mimecine** [StaticJsCMS/static-cms#1089]
Title says it all. 

```
    summary: "{{title}} - {{venue | upper | truncate(10,'...')}} - {{start}} to {{end | date('yyyy')}}"
    summary_fields: ["title","venue","start","end"]
    sortable_fields: 
      fields: ["title","venue","start","end"]
      default:
        field: "end"
        direction: Descending
```
The above exposes another problem: format filters do nothing.
I did try to prefix the fields like {{fields.start}} but there was no difference in behavior.
