### ISSUE TITLE
It should be possible to configure the toolbar font items

### ISSUE THREAD

**Issue by stoepekapel** [StaticJsCMS/static-cms#1096]
It should be possible to configure the toolbar font items ("paragraph", "Heading 1",...)"?  
As with many projects, users are not allowed to add an h1, for example

**Something like:**

```
  - label: Body
    name: body
    widget: markdown
    toolbar_buttons:
      main:
        - bold
        - italic
        - font
        - unordered-list
        - ordered-list
      selection:
        - bold
        - italic
      font:
        - paragraph
        - h3
        - h4
```
**or as buttons:**

```
  - label: Body
    name: body
    widget: markdown
    toolbar_buttons:
      main:
        - bold
        - italic
        - h3
        - h4
        - unordered-list
        - ordered-list
      selection:
        - bold
        - italic
```
