### ISSUE TITLE
TypeError: Cannot destructure property 'decorations' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by fimion** [StaticJsCMS/static-cms#245]
**Describe the bug**
Migrating from netlifycms, I'm hitting a bug when i get it into production on alex.party. Can't seem to make or edit posts. It's angry about something but i don't know what.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Static CMS version: ``
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46`

**CMS configuration**
```
backend:
  name: github
  repo: fimion/alex-party
  branch: master
media_folder: public/uploads
public_folder: /uploads
site_url: https://alex.party
display_url: https://alex.party
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{year}}/{{month}}/{{day}} - {{title}}"
    sortableFields:
      - pubDate
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: pubDate
        widget: datetime
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown
    sortable_fields:
      fields:
        - commit_date
        - title
        - commit_author
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
