### ISSUE TITLE
Relation widget not working

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#247]
When using the relation widget according to the documentation, I get the following error message:
```
Uncaught (in promise) Error: Not supported
    allEntriesByFolder https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:746
    listAllEntries https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    lct https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:1016
    lct https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:1016
    il https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    wu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    lu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Wr https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    nu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    jo https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Mo https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    p https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    uu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notifyNestedSubs https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    p https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    uu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notifyNestedSubs https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    f https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    TS https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:222
    dO https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    dispatch https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    U$/< https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:222
    dO https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    i https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iF https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:544
    setTimeout handler*iF</< https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:544
    il https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    wu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    lu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Wr https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    nu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    ns https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    push https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    o https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    p https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    onClick https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Me https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Ue https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    ji https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    ji https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Ii https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    qi https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    uu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Qe https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    qi https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Yt https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Bt https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Ni https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Fi https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Wi https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Wi https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    createRoot https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    init https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:1016
    <anonymous> http://localhost:1313/admin-new/#/collections/blog/entries/musikfahrt-2022:13
[static-cms-core.js:740:4114](https://cdn.jsdelivr.net/npm/@staticcms/core@1.0.0-beta4/dist/static-cms-core.js)
    lct https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:1016
    AsyncFunctionThrow self-hosted:812
    (Async: async)
    lct https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:1016
    il https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    wu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    _u https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    lu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    lu self-hosted:1412
    Wr https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    (Async: VoidFunction)
    iu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    nu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    jo https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    Mo https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    p https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    uu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notifyNestedSubs https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notifyNestedSubs self-hosted:1362
    p https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    uu https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notify https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    notifyNestedSubs https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    r https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    f https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    TS https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:222
    dO https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    dispatch https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    U$/< https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:222
    InterpretGeneratorResume self-hosted:1827
    AsyncFunctionNext self-hosted:807
    (Async: async)
    dO https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:149
    i https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
    iF https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:544
    (Async: setTimeout handler)
    iF https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:544
    il https://cdn.jsdelivr.net/npm/@staticcms/core@latest/dist/static-cms-core.min.js:14
```

my relation config:
```
- label: "Beitragsautor"
  name: "author"
  widget: "relation"
  collection: "author"
  search_fields: ["title"]
  value_field: "title"
```
my collection config:
```
- name: "author" 
    icon: "user"
    label: "Autoren" # Used in the UI
    label_singular: "Autoren"
    folder: "content/german/author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., yyyy-MM-dd-title.md
    editor:
     preview: false
    media_folder: '/static/media/people'
    public_folder: '/media/people'
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Hintergrundbild", name: "bg_image", widget: "hidden", default: "/media/backgrounds/page-title.png"}
      - {label: "Metabeschreibung", name: "description", widget: "text", default: "", required: false}
      - {label: "Gravatar-E-Mail", name: "email", widget: "string", required: false}
      - {label: "Foto", name: "image", widget: "image"}
      - label: "Kontaktdaten"
        label_singular: " "
        name: "social"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - label: "Symbol"
            name: "icon"
            widget: "select"
            options:
              - { label: "YouTube", value: "fa-brands fa-youtube" }
              - { label: "Twitter", value: "fa-brands fs-twitter" }
              - { label: "Pinterest", value: "fa-brands fa-pinterest" }
              - { label: "GitHub", value: "fa-brands fa-github" }
              - { label: "GitLab", value: "fa-brands fa-gitlab" }
              - { label: "Vimeo", value: "fa-brands fa-vimeo" }
              - { label: "Instagram", value: "fa-brands fa-instagram" }
              - { label: "Facebook", value: "fa-brands fa-facebook" }
              - { label: "E-Mail", value: "fa-solid fa-at" }
              - { label: "Sonstige", value: "fa-solid fa-share-nodes" }
          - {label: "Link", name: "link", widget: "string"}
        required: false
      - {label: "Beschreibung", name: "body", widget: "markdown"}
```
