### ISSUE TITLE
DateTime widget shows "T00:00:00.000+01:00" after date, when time_format: false

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#345]
![image](https://user-images.githubusercontent.com/75796723/212395157-01e15eed-085a-4b39-b856-fe181baa87a4.png)

**Describe the bug:**
This string appears after the date, even though `time_format: false`. It still works - format is "dd-MM-yyyy", and it saves the field on the actual file with that format.

**Expected behaviour:**
That string should not be there. Even though it doesn't appear in the file, it will be confusing to users.

**Config:**

```yaml
collections:
  - name: nyheter
    label: Nyheter
    label_singular: nyhet
    folder: src/data/nyheter
    create: true
    fields:
     - {label: Rubrik, name: title, widget: string, required: true}
     - {label: Datum, name: date, widget: datetime, time_format: false, format: "dd-MM-yyyy"} 
     - {label: Omslagsbild, name: img, widget: image, required: false}
     - {label: Utdrag, name: excerpt, widget: text, required: true, hint: "Detta är det som står på startsidans nyhetsflöden. Du behöver inte komma på nåt speciellt, copy pastea bara 3 första meningarna från inlägget"}
     - {label: Inlägget, name: body, widget: markdown, required: true}
```
