### ISSUE TITLE
`list` widgets' `field` option not recognized

### ISSUE THREAD

**Issue by CommanderStorm** [StaticJsCMS/static-cms#356]
For the `field` option of the `list` widget the markup should be the following:

```yaml
name: contributors
label: Contributors
widget: list
field:
  name: contributor
  label: Contributor
  widget: string
```

insted only the `fields`-option works:

```yaml
name: contributors
label: Contributors
widget: list
fields:
  - name: contributor
    label: Contributor
    widget: string
```

I would like to discuss how to correct this:
- **Option 1:** Delete the `field`-configuration option
- **Option 2:** Make this option work as a shorthand
