### ISSUE TITLE
Couldn't expand the nested folders

### ISSUE THREAD

**Issue by razonyang** [StaticJsCMS/static-cms#393]
Error as follows.

```log
ReferenceError: Cannot access '$' before initialization at https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:381:2229
at Object.Ga [as useMemo] (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:67437)
at t.useMemo (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:135476)
at https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:381:2153
at xa (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:63056)
at $s (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:74677)
at kl (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:120882)
at vc (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:108997)
at Oc (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:108925)
at gc (https://unpkg.com/@staticcms/app@%5E1.0.0/dist/static-cms-app.js:2:108788)
```

Configuration file

```yaml
backend:
  branch: main
  name: github
  repo: razonyang/hb-site
collections:
- create: true
  extension: md
  fields:
  - default: blog
    label: Layout
    name: layout
    widget: hidden
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: date
    widget: datetime
  - label: Featured Image
    name: thumbnail
    widget: image
  - label: Body
    name: body
    widget: markdown
  folder: content/news
  label: News
  name: news
  slug: '{{year}}/{{month}}/{{day}}/{{slug}}'
- create: true
  description: Documentation
  extension: md
  fields:
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: date
    widget: datetime
  - label: Featured Image
    name: thumbnail
    widget: image
  - label: Body
    name: body
    widget: markdown
  folder: content/docs
  i18n: true
  label: Docs
  label_singular: Doc
  name: docs
  nested:
    depth: 100
  slug: '{{slug}}'
i18n:
  defaultLocale: en
  locales:
  - en
  - zh-hans
  - zh-hant
  structure: multiple_files
locale: en
media_folder: static/images/uploads
search: true
site_url: http://localhost:13131/
```
