### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fimion** [StaticJsCMS/static-cms#412]
**Describe the bug**

I was typing up a new blog post, and apparently triggered a stack overflow.

**To Reproduce**

It is likely related to my custom preview component. 
https://github.com/fimion/alex-party/blob/872523065ce8859d5d3cf7c4fee7c2bb8f8473bb/src/pages/admin.astro#L36-L67

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Static CMS version: `1.0.0`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.61`

**CMS configuration**
```
backend:
  name: github
  repo: fimion/alex-party
  branch: master
logo_url: /favicon.svg
media_folder: public/uploads
public_folder: /uploads
site_url: https://alex.party
display_url: https://alex.party
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{pubDate}} - {{title}} - Draft: {{draft}}"
    sortable_fields:
      fields:
        - pubDate
      default:
        field: pubDate
        direction: Descending
    fields:
      - name: layout
        label: Layout
        widget: hidden
        default: ../../layouts/BlogPost.astro
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: pubDate
        widget: datetime
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: RSS Only
        name: rssOnly
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
