### ISSUE TITLE
Migration from netlify-cms

### ISSUE THREAD

**Issue by Mario8419** [StaticJsCMS/static-cms#431]
I followed all migration steps from docs but still netlify-cms opening on admin path.

- Git Gateway with Netlify backend
- removing all netlify-cms imports and components
- also did a clean npm
-latest version of static-cms

**Comment by Skrubbadubba** [comment]
If you are still getting netlify-cms, that means you must have missed something when replacing it.

- Did you remember to uninstall netlify-cms, besides simply installing static-cms?
- Is there a script loaded from CDN that you didn't change, perhaps someplace you forgot you had it?

Could you show your `admin/index.html`?

**Comment by Mario8419** [comment]
I uninstalled netlify-cms and netlify-cms-app components and of course gatsby-plugin-netlify-cms, changed import to @staticcms/core 

my static/admin/config.yml looks like this:

```
backend:
  name: git-gateway
  branch: main
  
locale: 'de'
media_folder: static/img
public_folder: /img

collections:

  - name: "blog"
    label: "News"
```

and my src/cms/cms.js looks like this:

```
import CMS, { de } from '@staticcms/core'
CMS.registerLocale('de', de)
CMS.init()
```
