### ISSUE TITLE
List Widget is not visible

### ISSUE THREAD

**Issue by Mario8419** [StaticJsCMS/static-cms#438]
List Widget is not showing up

- {label: "Tags", name: "tags", widget: "list", hint: "example, cms, etc.."}

only comment is shown and the field seems to be required despite not set as required

**Comment by denyskon** [comment]
You need to set a fields property for it to work:
```
- widget: "list"
  label: "Tags"
  ....
  fields:
    - {label: "Tag", widget: "string".....}
```
