### ISSUE TITLE
[next] Nested Collections not working as expected

### ISSUE THREAD

**Issue by timotheegoguely** [StaticJsCMS/static-cms#703]
I’m trying to use the [Nested Collections](https://next.staticcms.org/docs/migration-guide-v2#nested-collections) with [v2 beta.6](https://unpkg.com/@staticcms/app@2.0.0-beta.6/dist/static-cms-app.js), but I’m facing several problems:

- Nested folders do not display index files title as folders title is the sidebar: `Page 1b` instead of `Folder 1`, `Page 1.1b` instead of `Folder 1.1`… It should use the same titles used in the breadcrumb
- The pages inside subfolders (ex: `folder-1-1`) or not listed (see second screenshot bellow)
- There is no carret icon in front of folders containing subfolders in the sidebar (ex: `folder-1`)

![folder-1](https://user-images.githubusercontent.com/8271134/232469080-9058411b-c2f3-4a4f-a06b-5cf4c0a444c0.png)
![folder-1-1](https://user-images.githubusercontent.com/8271134/232469140-7bf83f50-52cf-43bd-85cb-2dd56aa59040.png)

Here is the `content/nested-folders/` I'm using for testing purposes (it's a Hugo website with `_index.md` as index files):

```
content
├── nested-folders
│   ├── _index.md
│   ├── folder-1
│   │   ├── _index.md
│   │   ├── folder-1-1
│   │   │   ├── _index.md
│   │   │   ├── page-1-1a.md
│   │   │   └── page-1-1b.md
│   │   ├── page-1a.md
│   │   └── page-1b.md
│   ├── folder-2
│   │   ├── _index.md
│   │   ├── page-2a.md
│   │   └── page-2b.md
│   ├── folder-3
│   │   ├── _index.md
│   │   ├── page-3a.md
│   │   └── page-3b.md
│   └── folder-4
│       ├── _index.md
│       ├── page-4a.md
│       └── page-4b.md
```

And here is my `config.yml`
```yaml
collections:
  - name: nested-folders
    label: Nested folders
    folder: content/nested-folders
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
      path: { label: 'Path', index_file: '_index' }
    extension: md
    format: yaml-frontmatter
    fields:
      - { label: "Draft", name: draft, widget: boolean }
      - { label: "Title", name: title, widget: string }
      - { label: "Description", name: description, widget: string, required: false }
      - { label: "Date", name: date, widget: datetime, date_format: 'dd/MM/yyyy', time_format: false, format: "yyyy-MM-dd"}
      - { label: "Image", name: image, widget: image, choose_url: true, required: false }
      - { label: "Body", name: body, widget: markdown }
```
