### ISSUE TITLE
RangeError: Use `yyyy` instead of `YYYY` (in `YYYY-MM-DDTHH:mm:ssZ`) for formatting years 

### ISSUE THREAD

**Issue by KtorZ** [StaticJsCMS/static-cms#757]
**Describe the bug**

Seems like date formats are quite picky / case-sensitive. Note that the workaround is obvious, but I thought I'd still report the issue. Cheers. 

**To Reproduce**

Specify a date format, with capitalised date template (e.g. `YYYY`). I suppose it also happens for months and days.

**Expected behavior**

Either, the format is accepted or a proper error message is raised.

**Screenshots**

<img width="790" alt="image" src="https://user-images.githubusercontent.com/5680256/234026573-2fedc34a-84b3-4328-ab16-6bd8b9fbe00e.png">

**Applicable Versions:**
 - Static CMS version: `2.0.0`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0`

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: static
public_folder: /
locale: fr
collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    editor:
      preview: false
    summary: "{{date | date('YYYY-MM-DD')}} | {{title}}"
    preview_path: blog/{{year}}/{{month}}/{{slug}}
    fields: [ ... ]
```
