### ISSUE TITLE
Template variables in folder collection path

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#785]
```yaml
    ...
    media_folder: "public/media/content/",
    public_folder: "/media/content",
    ...
    collections: [
      {...
        folder: "src/pages/",
        path: "{{slug}}/index",
        media_folder: "{{slug}}",
        public_folder: "/media/content",
      }
    ]
```

> **From Discord:**
> When I set a direct path yes it works, but not with {{slug}}.
When I uploaded a picture it was uploaded under /media/content/{{slug}} but it created a special "{{slug}}" folder. Mission not accomplished :/
