### ISSUE TITLE
Datetime Widget Issue

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#786]
**Error:**
> **From Discord:**
> I have a collection with some fields that use a date_format and time_format, but the underlying storage format has always been the default. When I run locally with a proxy server, the inputs that render the dates are empty.

When I run a production build (I'm using NextJS), then attempting to load the same entry crashes the whole app

![image](https://github.com/StaticJsCMS/static-cms/assets/1388138/e3aa54d2-c60f-4758-86b8-daeb95a250fe)
![image](https://github.com/StaticJsCMS/static-cms/assets/1388138/dce26385-5796-4672-8a79-f0e84c7ca80f)

**Config:**
```yaml
  {
        label: 'Publish Date',
        name: 'publishDate',
        widget: 'datetime',
        date_format: 'LLLL d, yyyy',
        time_format: 'h:mm bbb',
        format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
      },
      {
        label: 'Event Date',
        name: 'eventDate',
        widget: 'datetime',
        date_format: 'LLLL d, yyyy',
        time_format: false,
        format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
      },
```

**Data:**
```js
{
  "publishDate": "2023-04-13T23:39:31-07:00",
  "eventDate": "2023-06-23T00:00:00-07:00",
}
```
