### ISSUE TITLE
broken object header in list items

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#796]
When using an object as one of the fields for a list element, the object header isn't being displayed.
![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/d823fecb-0a50-4cae-91eb-f273d9f388bd)

config:
```yaml
- label: "Kreative Haufen"
        name: "topics"
        widget: "list"
        required: false
        fields:
          - {label: "Titel", name: "title", widget: "string", required: true}
          - {label: "Inhalt", name: "content", widget: "markdown", required: true}
          - label: "Superhaufen"
            name: "superhaufen"
            widget: "object"
            required: false
            fields:
              - {label: "Aktivieren", name: "enable", widget: "boolean", required: false}
              - label: "Superhaufen"
                name: "link"
                widget: "relation"
                collection: "superhaufen"
                search_fields: ["title"]
                value_field: "title"
                required: false
                collapsed: true
```
Without a header, it is sometimes unclear where the fields do belong
