### ISSUE TITLE
TypeError: can't access property "length", dq is undefined

### ISSUE THREAD

**Issue by johnboylesingfield** [StaticJsCMS/static-cms#799]
**Describe the bug**
Adding a markdown widget crashes the admin UI. I am using Next.js 13 with the app directory and Static CMS internationalization.

**To Reproduce**
https://github.com/johnboylesingfield/john-boyle-singfield

**Expected behavior**
Markdown widgets to be added without issues.

**Screenshots**
![screenshot](https://github.com/StaticJsCMS/static-cms/assets/82598494/e555613d-629e-4899-a21a-147fbe17f215)

**Applicable Versions:**
 - Static CMS version: `static-cms@2.2.0`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0`

**CMS configuration**
```
backend:
  name: github
  repo: johnboylesingfield/john-boyle-singfield
  branch: main
media_folder: /public/files
public_folder: /files
site_url: https://lighthearted-zabaione-364712.netlify.app/
i18n: &a1
  structure: multiple_folders
  locales:
    - fr
    - en
  defaultLocale: fr
collections:
  - name: works
    label: Works
    label_singular: Work
    folder: content/works
    create: true
    slug: "{{slug}}"
    i18n: *a1
    fields:
      - label: Title
        name: title
        widget: string
        i18n: translate
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Url
        name: url
        widget: string
        i18n: translate
        required: false
      - label: Image
        name: image
        widget: image
        i18n: translate
        required: false
        media_library: {}
      - label: File
        name: file
        widget: file
        i18n: translate
        required: false
        media_library: {}
      - label: Description
        name: description
        widget: markdown
        i18n: translate
        required: false
        media_library: {}
    media_library: {}
    sortable_fields:
      fields:
        - commit_date
        - title
        - date
        - commit_author
        - description
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
display_url: https://lighthearted-zabaione-364712.netlify.app/

```

**Additional context**

As always, thanks for the help!
