### ISSUE TITLE
[feature] key/value pairs widget

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#828]
For long parameter lists, it would be nice to have a widget which outputs an object, but where you can set the field name and its value from the UI.

example output data:
```yaml
params:
  param1: value1
  param2: value2
  ...
```

The UI for it would consist of a list with two string widgets, one for parameter name and one for its value.
