### ISSUE TITLE
RangeError: Use `yyyy` instead of `YYYY` (in `YYYY-MM-DD`) for formatting years to the input `Thu...

### ISSUE THREAD

**Issue by designbytk** [StaticJsCMS/static-cms#850]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Static CMS version: ``
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: static-cms
media_folder: src/11ty/_includes/assets/images
public_folder: assets/images
local_backend: true
collections:
  - label: Blog A-G
    name: a-e
    folder: src/11ty/posts/a-g
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - widget: datetime
        label: Publish Date
        name: date
        format: YYYY-MM-DD
        time_format: false
      - label: Body
        name: body
        widget: markdown
        media_library: {}
      - widget: select
        label: Category
        name: categories
        multiple: false
        create: true
        options:
          - Tags
          - created
          - from
          - config.yml
      - widget: list
        label: Tags
        name: tags
        multiple: true
        create: true
    media_library: {}
    sortable_fields:
      fields:
        - commit_date
        - title
        - date
        - commit_author
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

```

**Additional context**
