### ISSUE TITLE
Relation Widget for file, search not updating results

### ISSUE THREAD

**Issue by preetamslot** [StaticJsCMS/static-cms#853]
It looks like the UI is not updating on  search.

field:
```
{
	name: 'icons',
	label: t('icon'),
	widget: 'relation',
	collection: 'config',
	required: false,
	file: 'src/content/config/icon_list.mdx',
	search_fields: ['icons.*.name'],
	display_fields: ['icons.*.name'],
	options_length: 200,
	value_field: 'icons.*.icon'
},
```

icon_list:
```
icons:
  - name: right
    icon: /src/icons/right.svg
  - name: left
    icon: /src/icons/left.svg
  - name: download
    icon: /src/icons/download.svg
    ...
 - name: zoom
    icon: /src/icons/zoom.svg

```
search for "zoom" (last icon in the list)
![image](https://github.com/StaticJsCMS/static-cms/assets/5420582/28e45257-c5ef-4166-bc6c-d8c69344b111)

Search for name that is not in the icons:
![image](https://github.com/StaticJsCMS/static-cms/assets/5420582/61dd1c58-2e8a-4c4f-82de-a9a4a574942d)

how can I fix this?

p.s this field/widget is nested
