### ISSUE TITLE
i18n Issue

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#903]
I wonder if it is a known issue, I was trying i18n support for collections but added entries would not show up in the list of collection. Also noticed that 'identifier_field' collections configuration does not seem to work since the field is nested under language (for example, en.name is not valid). Thank you for your attention in advance. Tested config is as follows as shown in the documentation site (https://staticjscms.netlify.app/docs/i18n-support) 

```yaml
i18n: {
  structure: 'single_file',
  locales: ['en', 'de', 'fr']
},
collections: [
  {
    name: 'posts',
    label: 'Posts',
    folder: 'content/posts',
    create: true,
    i18n: true,
    fields: [
      { label: 'Title', name: 'title', widget: 'string', i18n: true },
      { label: 'Date', name: 'date', widget: 'datetime', i18n: 'duplicate' },
      { label: 'Body', name: 'body', widget: 'markdown' },
    ],
  },
],
```

I have tried i18n with the next.js / staticcms template (using staticcms/core version 3.3.3) and I recreated the issue. Please find the config of the test site: https://github.com/shumiyao/static-cms-next-netlify-template/blob/main/src/config.ts

https://media.discordapp.net/attachments/1047324110499360808/1155603893800153098/ScreenShot_2023-09-24_at_9.36.23_PM.JPG?ex=651c7b7e&is=651b29fe&hm=585e1b7047e2a84fde09843637c3495db1b1eeaad870035b7a8528e7f15eef0f&=&width=2319&height=1357
