### ISSUE TITLE
Setting media_folder on a file widget results in empty media selection on image widget

### ISSUE THREAD

**Issue by preetamslot** [StaticJsCMS/static-cms#939]
To make it work you have to declare `media_folder` on both widgets.

```
 {
              label: t("video"),
              name: "video",
              choose_url: true,
              media_folder: "public/video",
              hint: t("video_hint"),
              widget: "file",
              required: false,
               
            },
             {
              label: t("image"),
              name: "thumbnail",
              widget: "image",
              required: true,
            },

```

**Comment by KaneFreeman** [comment]
Can you clarify what you mean by an `empty media selection`? Can you provide a video of this happening or a repository where this issue occurs?

**Comment by preetamslot** [comment]
Sorry for the late reply!

the bug is that if you declare a `media_folder` on one file field you have to declare it on all file fields.
Declaring it on one (in this case video) the thumbnail field wont work, it does not use the default "media folder" settings

**Comment by KaneFreeman** [comment]
One thing of note, though, keep in mind that `media_folder` can take an absolute (starts with `/`) or relative path (does not start with `/`). If you provide a relative path (like you have here, `media_folder: "public/video",`) then it will always be relative to the entry's file location.

**Comment by preetamslot** [comment]
> Could you provide your full configuration? Or at least this collections configuration and what your global `medai_folder` configuration is?

```
const config = {
  locale: lang,
  site_url: url,
  logo_url: "https://nebulix.unfolding.io/logo.svg",
  local_backend: true,
  backend: {
    name: "test-repo",
  },
  search: "true",
  media_folder: "src/assets",
  public_folder: "/src/assets",
  media_library: {
    max_file_size: 8012000,
    folder_support: true,
  },
  collections: [page, post, settings],
};
```

**Comment by KaneFreeman** [comment]
It looks like your collections (page, post, settings) are stored elsewhere. Can you provide the collection configuration for the one having trouble please?

**Comment by preetamslot** [comment]
The project I am working on I based of a other template I made,
here you can see the collections
https://github.com/unfolding-io/nebulix/tree/main/src/cms

**Comment by KaneFreeman** [comment]
I am having a lot of trouble replicating your issue. It might be more helpful to know what you are attempting to accomplish.

Right now If I use your config and put in a video field where there is another image or file widget that doesn't have a `media_folder` configured it is putting it where it should be.

## Example

```yaml
locale: en
logo_url: 'https://nebulix.unfolding.io/logo.svg'
local_backend: true
backend:
  name: github
  branch: main
  repo: staticjscms/static-cms-github
search: 'true'
media_folder: src/assets
public_folder: /src/assets
media_library:
  max_file_size: 2012000
  folder_support: true
collections:
  - name: page
    identifier_field: name
    folder: src/content/page
    label: Pages
    format: frontmatter
    extension: mdx
    icon: page
    create: true
    editor:
      preview: false
      frame: false
    fields:
      - label: Title
        name: title
        widget: string
        pattern:
          - '.{5,}'
          - Must have at least 20 characters
      - label: Body
        name: body
        widget: markdown
        required: false
        show_raw: true
      - label: Video
        name: "video"
        choose_url: true
        media_folder: "public/video"
        hint: Video Hint
        widget: "file"
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        required: true
      - label: OG Image
        name: og_image
        widget: image
        required: false
        hint: OG Image here!
```

If you fill that out and save, it saving like this:

```
video: src\content\page\public\video\video-name.mp4
thumbnail: /src/assets/thumbnail.png
og_image: /src/assets/og_image.jpg
```
