### ISSUE TITLE
Getting Git gateway issue on Chrome, but never on Firefox.

### ISSUE THREAD

**Issue by mar-ver** [StaticJsCMS/static-cms#960]
Hi, 
When trying to login on Static CMS on Firefox, I can login without issues. I have cleared cookies and it still works. I tried safari and it also works. 

However, when trying to login on chrome and opera it doesn't work. I have tried clearing cache and cookies, using incognito mode, etc. Nothing is working, I get: 

`Git Gateway Error: Please ask your site administrator to reissue the Git Gateway token.`

I have of course tried reissuing the Git gateway token but since it works in Firefox and Safari I don't think that's the problem. 

My confg file looks like that.  Below is the error in chrome. 

Config.yml
```
backend:
  name: git-gateway
  repo: lauracantarella/lauracanterella.it
  base_url: https://laura-cantarella-site.netlify.app/

  branch: main # Branch to update (optional; defaults to main)

local_backend: true

media_folder: "src/_static/images"
public_folder: "/_static/images"


media_library:
  name: Media
  max_file_size: 4000000

logo_url: '/_static/icons/android-chrome-192x192.png'

collections:

  
```
index.html
```
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://unpkg.com/@staticcms/app@^2.0.0/dist/main.css" />
    <title>Content Manager</title>
  </head>
  <body>
    <!-- Include the script that builds the page and powers Static CMS -->
    <script src="https://unpkg.com/@staticcms/app@^2.0.0/dist/static-cms-app.js"></script>
    <script>
      window.CMS.init();



      CMS.registerPreviewStyle('https://unpkg.com/bamboo.css/dist/light.min.css');
      CMS.registerPreviewStyle('li > div { padding: 10px; margin: 3px; border: 1px solid grey; background-color: white; border-radius: 20px; color: black; } li{ padding: 30px 20px; border-bottom: 3px black dotted; list-style: none; margin: 0 20px 0 0;} label + ul {background-color: lightblue; black; border-radius: 0 20px 20px 20px; list-style: none } label {width: fit-content; background-color: lightblue; padding: 10px; border-radius: 10px 10px 0 0; margin-bottom: 0;}', { raw: true });

    </script>aa
    <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>

  </body>
 
</html>
 
```

<img width="745" alt="chrome" src="https://github.com/StaticJsCMS/static-cms/assets/64637402/e783a914-a417-4f24-98a6-909241b53a71">
