### ISSUE TITLE
YAMLParseError: Unexpected scalar at node end at line

### ISSUE THREAD

**Issue by preetamslot** [StaticJsCMS/static-cms#963]
I get this error on a file, but I cant pinpoint what is wrong.

```
static-cms-app.js:11 YAMLParseError: Unexpected scalar at node end at line 25, column 18:

        href: "#"
```
**Setting:**
```
{
      name: "navigation",
      label: t("navigation"),
      file: "src/content/config/navigation.mdx",
      fields: [
        {
          name: "main_menu",
          label: t("main_menu"),
          widget: "list",
          collapsed: true,
          fields: [
            { name: "label", label: t("label"), widget: "string" },
            { name: "href", label: t("href"), widget: "string" },
          ],
        },
        {
          name: "footer_menus",
          label: t("footer_menus"),
          widget: "list",
          collapsed: true,
          reuired: false,
          fields: [
            { name: "label", label: t("label"), widget: "string" },
            {
              name: "links",
              label: t("links"),
              widget: "list",
              collapsed: true,
              fields: [
                { name: "label", label: t("label"), widget: "string" },
                { name: "href", label: t("href"), widget: "string" },
              ],
            },
          ],
        },
         
      ],
    },

```
**File**
```
---
main_menu:
  - label: News
    href: /news
  - label: Features
    href: "#features"
  - label: About
    href: "#about"
  - label: Contact
    href: "#contact"
footer_menus:
  - label: Company
    links:
      - label: Home
        href: /
      - label: "Privacy Policy "
        href: "#"
      - label: About us
        href: "#"
  - label: Documentation
    links:
      - label: Docs
        href: "#"
      - label: Blog
        href: "#"
---

```
