### ISSUE TITLE
Support string / number only lists

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#97]
> Can we have a List widget that's just an array of strings, because right now for the List component, it has to be an array of objects like this
> <img width="292" alt="image" src="https://user-images.githubusercontent.com/35210888/204331754-765abfd8-e874-4540-919f-0e186e019249.png">
but for the tags on my blog I just want an array of strings
> <img width="109" alt="image" src="https://user-images.githubusercontent.com/35210888/204331881-84c0e4c7-c8d2-42b8-bdd3-6e1aba819f6e.png">

_Originally posted by @robigan in https://github.com/StaticJsCMS/static-cms/discussions/4#discussioncomment-4255287_

**Comment by robigan** [comment]
I tried to make my own widget based off of the List widget but my dev environment kept crashing and I can hardly understand the code as it's just so vertical and not commented

**Comment by robigan** [comment]
Most likely my node version but I'll figure that out later

**Comment by robigan** [comment]
Actually @KaneFreeman what node version do you use?

**Comment by robigan** [comment]
Hmm

**Comment by robigan** [comment]
Turns out it has got to do with some strange error in port number https://stackoverflow.com/questions/70854917/webpackdevserver-crashing-with-error-rsv1-must-be-clear

**Comment by robigan** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/35210888/204469205-d0c0b9eb-6f2b-499c-af74-b3989fcce25f.png">
Getting somewhere

**Comment by robigan** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/35210888/204469205-d0c0b9eb-6f2b-499c-af74-b3989fcce25f.png">
> Getting somewhere

@KaneFreeman How would you propose implementing the removal of an item from an array

**Comment by onodera-punpun** [comment]
I did this on netlifyCMS using the following extension:

```js
// See: https://github.com/netlify/netlify-cms/issues/4646 -->
var ArrayControl = createClass({
	handleChange: function (e) {
		const separator = this.props.field.get("separator", ", ");
		this.props.onChange(e.target.value.split(separator));
	},

	render: function () {
		const separator = this.props.field.get("separator", ", ");
		var value = this.props.value;

		return h("input", {
			id: this.props.forID,
			className: this.props.classNameWrapper,
			type: "text",
			value: value ? value.join(separator) : "",
			onChange: this.handleChange,
		});
	},
});

var ArrayPreview = createClass({
	render: function () {
		return h(
			"ul",
			{},
			this.props.value.map(function (val, index) {
				return h("li", { key: index }, val);
			})
	);
	},
});

var schema = {
	properties: {
		separator: { type: "string" },
	},
};

CMS.registerWidget("array", ArrayControl, ArrayPreview, schema);
```

**Comment by KaneFreeman** [comment]
> > <img alt="image" width="697" src="https://user-images.githubusercontent.com/35210888/204469205-d0c0b9eb-6f2b-499c-af74-b3989fcce25f.png">
> > Getting somewhere
> 
> @KaneFreeman How would you propose implementing the removal of an item from an array

Make a copy of the array, then use splice.

```js
const newValue = [...oldValue];
newValue.splice(index, 1);
```

**Comment by robigan** [comment]
> ```js
> separator
> ```

This is just a string separated by commas, neat implementation but am trying to integrate into the existing code base and use a UI similar to the one I have presented above

**Comment by robigan** [comment]
> > @KaneFreeman How would you propose implementing the removal of an item from an array
> 
> Make a copy of the array, then use splice.
> 
> ```js
> const newValue = [...oldValue];
> newValue.splice(index, 1);
> ```

I mean UI wise

**Comment by KaneFreeman** [comment]
Ideally this would just be an extension of the existing `List` widget, which already handles addition, deletion and reordering. Best approach here would be to change the `List` widget to accept a `string` or `number` array in addition to an `object` array and simply render them as if they were objects with the respective widgets under them.

So an array of strings and an array of objects with one `string` widget in it would render identically, but save differently.

An array of numbers and an array of objects with one `number` widget in it would render identically, but save differently.

**Comment by robigan** [comment]
Very well then, cus I had 3 different ideas for implementation, but I'll work on that.
Btw Kane, for specifying this in config.yml, should I use a field: widget_config or just the standard fields: widget_config[]? Note that NetlifyCMS supports both field and fields on the list component

**Comment by robigan** [comment]
@KaneFreeman I have tried the best to my knowledge of the code base to implement this feature for the List widget, I would appreciate if you could look at my branch and figure out what has to be done for the value field to be correctly passed because I am unsure about how to do it at this point.

**Comment by KaneFreeman** [comment]
I've been thinking on this some more, and re-adding `field` creates some issues elsewhere in the app too, not just in the widget itself. `field` was used by NetlifyCMS's `select`, `object` and `list` widgets, and I removed it during the rewrite to attempt and simplify the setup. I don't quite like the idea of reverting that simplification.

So after thinking it over, I believe the best and simplest approach would be to add some simple logic to the input/output of the `list` widget that when a single field exists in the list's `fields` it stores it DOES NOT wrap the value in an object. This will keep the logic for this change isolated to the `list` widget.

### Examples

#### Single Field

**Field Setup**
```yaml
name: testimonials
label: Testimonials
widget: list
summary: '{{fields.quote}} - {{fields.author.name}}'
fields:
  - name: quote
    label: Quote
    widget: string
    default: Everything is awesome!
```

**Output**
```yaml
testimonials:
  - A testimonial
  - Another testimonial
  - Yet one more testimonial
```

#### Multiple Fields

**Field Setup**
```yaml
name: testimonials
label: Testimonials
widget: list
summary: '{{fields.quote}} - {{fields.author.name}}'
fields:
  - name: quote
    label: Quote
    widget: string
    default: Everything is awesome!
  - name: author
    label: Author
    widget: object
    fields:
      - name: name
        label: Name
        widget: string
        default: Emmet
      - name: avatar
        label: Avatar
        widget: image
        default: /img/emmet.jpg
```

**Output**
```yaml
testimonials:
  - quote: A testimonial
    author:
      name: Bob
      avatar: /img/bob.jpg
  - quote: Another testimonial
    author:
      name: Sam
      avatar: /img/sam.jpg
  - quote: Yet one more testimonial
    author:
      name: Billy
      avatar: /img/billy.jpg
```
