### ISSUE TITLE
Local Backend does not work local_backend parameter gets essentially ignored.

### ISSUE THREAD

**Issue by mnordhaus** [StaticJsCMS/static-cms#989]
Please have a look into the following discussion: 

https://github.com/StaticJsCMS/static-cms/discussions/986#discussion-5859415

It seems that it is a bug.

My backend configuration:

```yaml
backend:
  name: git-gateway
  branch: main
  local_backend: true
```
Proxy is running on default port. 

Netlyfy identitiy gets still invoked and changes saved to github.

Staticcms Version is 3.4.5. The Issue happens in both in the current version of Chrome and Safari
